### ISSUE TITLE
Leaderboards not loading

### ISSUE THREAD

**Issue by Nilstrieb** [C0RR1T/wisliger-casino#10]
![image](https://user-images.githubusercontent.com/48135649/126595330-bab7e9b0-e390-4c8b-9a18-1926e826f721.png)
![image](https://user-images.githubusercontent.com/48135649/126595339-66ffbee9-aa2e-4893-9da9-299325a2c057.png)

**Comment by Nilstrieb** [comment]
(also maybe don't use the development build of the Firebse JS SDK?)

**Comment by C0RR1T** [comment]
I don't know how you don't use dev firebase sdk help

**Comment by C0RR1T** [comment]
Im currently working on a new version of WC, so please wait for the release of mentioned version.

**Comment by C0RR1T** [comment]
I just noticed it was an error with Firebase, so it should work now.
